---
title: Home
---

{% extends "../layouts/home.html.swig" %}
{% block content %}

  <section id="ui">
    <h3>User Interface</h3>

    <aside>
      <h1>Clean<br/>User<br/>Interfaces</h1>

      <div class="button">
        View portfolio
      </div>
    </aside>

    <figure>
      <img src="{{ site.url }}assets/images/anvelocom-archive-laptop-front-3x.png">
    </figure>
  </section>

{% endblock %}
